/**
 * Static emoji data: name-to-keyword map and category definitions.
 * Auto-extracted from emoji-picker.js to reduce file size.
 */

/**
 * Generic emoji picker component.
 * Used for both message composition and reactions.
 *
 * @example
 * // Anchored to a button (message input)
 * showEmojiPicker({ anchor: btnEmoji, onSelect: (emoji) => insertEmoji(emoji) });
 *
 * // Positioned at coordinates (reactions)
 * showEmojiPicker({ x: 100, y: 200, onSelect: (emoji) => react(emoji) });
 */

/** @type {Map<string, string>} */
export const EMOJI_NAMES = new Map(
  Object.entries({
    '😀': 'grinning face happy',
    '😃': 'smiley happy',
    '😄': 'smile happy',
    '😁': 'grin beaming',
    '😆': 'laughing satisfied',
    '😅': 'sweat smile nervous',
    '🤣': 'rofl rolling floor laughing',
    '😂': 'joy tears laughing cry',
    '🙂': 'slightly smiling',
    '🙃': 'upside down',
    '😉': 'wink',
    '😊': 'blush happy shy',
    '😇': 'innocent angel halo',
    '🥰': 'smiling hearts love',
    '😍': 'heart eyes love',
    '🤩': 'star struck excited',
    '😘': 'kissing heart blow kiss',
    '😗': 'kissing',
    '😚': 'kissing closed eyes',
    '😙': 'kissing smiling',
    '🥲': 'smiling tear sad happy',
    '😋': 'yum delicious tongue',
    '😛': 'tongue out',
    '😜': 'wink tongue crazy',
    '🤪': 'zany crazy wild',
    '😝': 'squinting tongue',
    '🤑': 'money mouth rich',
    '🤗': 'hugging hug',
    '🤭': 'hand over mouth oops giggle',
    '🤫': 'shushing quiet secret',
    '🤔': 'thinking hmm',
    '🫡': 'salute',
    '🤐': 'zipper mouth shut up',
    '🤨': 'raised eyebrow skeptical',
    '😐': 'neutral face',
    '😑': 'expressionless',
    '😶': 'no mouth silent',
    '🫥': 'dotted line face hidden',
    '😏': 'smirk',
    '😒': 'unamused annoyed',
    '🙄': 'rolling eyes',
    '😬': 'grimacing awkward',
    '🤥': 'lying pinocchio',
    '😌': 'relieved peaceful',
    '😔': 'pensive sad thoughtful',
    '😪': 'sleepy tired',
    '🤤': 'drooling',
    '😴': 'sleeping zzz',
    '😷': 'mask sick medical',
    '🤒': 'thermometer fever sick',
    '🤕': 'bandage hurt injured',
    '🤢': 'nauseated sick green',
    '🤮': 'vomiting sick throw up',
    '🥵': 'hot face sweating',
    '🥶': 'cold face freezing',
    '🥴': 'woozy drunk',
    '😵': 'dizzy knocked out',
    '🤯': 'exploding head mind blown',
    '🤠': 'cowboy hat',
    '🥳': 'party celebration',
    '🥸': 'disguise glasses nose',
    '😎': 'sunglasses cool',
    '🤓': 'nerd glasses',
    '🧐': 'monocle curious',
    '😕': 'confused',
    '🫤': 'diagonal mouth',
    '😟': 'worried',
    '🙁': 'slightly frowning',
    '☹️': 'frowning sad',
    '😮': 'open mouth surprised wow',
    '😯': 'hushed',
    '😲': 'astonished shocked',
    '😳': 'flushed embarrassed',
    '🥺': 'pleading puppy eyes',
    '🥹': 'holding back tears',
    '😦': 'frowning open mouth',
    '😧': 'anguished',
    '😨': 'fearful scared',
    '😰': 'anxious sweat',
    '😥': 'sad relieved',
    '😢': 'crying tear sad',
    '😭': 'sobbing crying loud',
    '😱': 'screaming fear horror',
    '😖': 'confounded',
    '😣': 'persevering determined',
    '😞': 'disappointed sad',
    '😓': 'downcast sweat',
    '😩': 'weary tired',
    '😫': 'tired exhausted',
    '🥱': 'yawning bored tired',
    '😤': 'huffing angry triumph',
    '😡': 'pouting angry mad',
    '😠': 'angry mad',
    '🤬': 'swearing cursing symbols',
    '😈': 'smiling devil horns',
    '👿': 'angry devil',
    '💀': 'skull dead death',
    '☠️': 'skull crossbones death poison',
    '💩': 'poop poo shit',
    '🤡': 'clown',
    '👹': 'ogre monster',
    '👺': 'goblin tengu',
    '👻': 'ghost boo halloween',
    '👽': 'alien ufo',
    '👾': 'space invader game alien',
    '🤖': 'robot',
    '😺': 'smiling cat',
    '😸': 'grinning cat',
    '😹': 'cat joy tears',
    '😻': 'heart eyes cat love',
    '😼': 'smirk cat',
    '😽': 'kissing cat',
    '🙀': 'weary cat shocked',
    '😿': 'crying cat sad',
    '😾': 'pouting cat angry',
    '👋': 'wave hello hi bye',
    '🤚': 'raised back hand',
    '🖐️': 'hand splayed fingers',
    '✋': 'raised hand stop high five',
    '🖖': 'vulcan spock',
    '👌': 'ok okay perfect',
    '🤌': 'pinched fingers italian',
    '🤏': 'pinching small tiny',
    '✌️': 'peace victory two',
    '🤞': 'crossed fingers luck hope',
    '🤟': 'love you gesture rock',
    '🤘': 'rock on horns metal',
    '🤙': 'call me shaka hang loose',
    '👈': 'pointing left',
    '👉': 'pointing right',
    '👆': 'pointing up',
    '🖕': 'middle finger',
    '👇': 'pointing down',
    '☝️': 'index pointing up',
    '👍': 'thumbs up like good yes',
    '👎': 'thumbs down dislike bad no',
    '✊': 'raised fist power',
    '👊': 'fist bump punch',
    '🤛': 'left fist bump',
    '🤜': 'right fist bump',
    '👏': 'clap clapping applause bravo',
    '🙌': 'raising hands celebration hooray',
    '👐': 'open hands',
    '🤲': 'palms up together',
    '🤝': 'handshake deal agreement',
    '🙏': 'pray please thank you folded hands',
    '💪': 'muscle strong bicep flex',
    '❤️': 'red heart love',
    '🧡': 'orange heart',
    '💛': 'yellow heart',
    '💚': 'green heart',
    '💙': 'blue heart',
    '💜': 'purple heart',
    '🖤': 'black heart',
    '🤍': 'white heart',
    '🤎': 'brown heart',
    '💔': 'broken heart',
    '❤️‍🔥': 'heart fire burning',
    '❤️‍🩹': 'mending heart healing',
    '❣️': 'heart exclamation',
    '💕': 'two hearts love',
    '💞': 'revolving hearts',
    '💓': 'beating heart',
    '💗': 'growing heart',
    '💖': 'sparkling heart',
    '💘': 'heart arrow cupid',
    '💝': 'heart ribbon gift',
    '💟': 'heart decoration',
    '🐶': 'dog puppy',
    '🐱': 'cat kitty',
    '🐭': 'mouse',
    '🐹': 'hamster',
    '🐰': 'rabbit bunny',
    '🦊': 'fox',
    '🐻': 'bear',
    '🐼': 'panda',
    '🐨': 'koala',
    '🐯': 'tiger',
    '🦁': 'lion',
    '🐮': 'cow',
    '🐷': 'pig',
    '🐸': 'frog',
    '🐵': 'monkey',
    '🙈': 'see no evil monkey',
    '🙉': 'hear no evil monkey',
    '🙊': 'speak no evil monkey',
    '🐔': 'chicken',
    '🐧': 'penguin',
    '🐦': 'bird',
    '🦅': 'eagle',
    '🦉': 'owl',
    '🐺': 'wolf',
    '🐴': 'horse',
    '🦄': 'unicorn magic',
    '🐝': 'bee honey',
    '🦋': 'butterfly',
    '🐢': 'turtle tortoise',
    '🐍': 'snake',
    '🐙': 'octopus',
    '🐬': 'dolphin',
    '🐳': 'whale',
    '🦈': 'shark',
    '🐘': 'elephant',
    '🦒': 'giraffe',
    '🌵': 'cactus',
    '🎄': 'christmas tree',
    '🌲': 'evergreen tree',
    '🌳': 'tree',
    '🌴': 'palm tree',
    '🌱': 'seedling sprout',
    '🌿': 'herb leaf',
    '🍀': 'four leaf clover lucky',
    '🌺': 'hibiscus flower',
    '🌻': 'sunflower',
    '🌹': 'rose flower',
    '🌷': 'tulip',
    '🌼': 'blossom',
    '🌸': 'cherry blossom sakura',
    '💐': 'bouquet flowers',
    '🌈': 'rainbow',
    '🍇': 'grapes',
    '🍉': 'watermelon',
    '🍊': 'orange tangerine',
    '🍋': 'lemon',
    '🍌': 'banana',
    '🍍': 'pineapple',
    '🍎': 'apple red',
    '🍏': 'apple green',
    '🍑': 'peach',
    '🍒': 'cherries',
    '🍓': 'strawberry',
    '🍔': 'hamburger burger',
    '🍟': 'fries french fries',
    '🍕': 'pizza',
    '🌭': 'hot dog',
    '🌮': 'taco',
    '🌯': 'burrito',
    '🍳': 'cooking egg fried',
    '🍲': 'pot food stew',
    '🍿': 'popcorn',
    '🍩': 'donut doughnut',
    '🍪': 'cookie',
    '🎂': 'birthday cake',
    '🍰': 'cake shortcake',
    '🍫': 'chocolate',
    '🍬': 'candy sweet',
    '🍭': 'lollipop',
    '🍦': 'ice cream',
    '☕': 'coffee hot beverage',
    '🍵': 'tea',
    '🍶': 'sake',
    '🍾': 'champagne bottle celebration',
    '🍷': 'wine glass',
    '🍸': 'cocktail martini',
    '🍺': 'beer mug',
    '🍻': 'clinking beers cheers',
    '🥂': 'clinking glasses champagne toast cheers',
    '⚽': 'soccer football',
    '🏀': 'basketball',
    '🏈': 'football american',
    '⚾': 'baseball',
    '🎾': 'tennis',
    '🏐': 'volleyball',
    '🏉': 'rugby',
    '🎱': 'billiards pool',
    '🏓': 'ping pong table tennis',
    '⛳': 'golf',
    '🏹': 'bow arrow archery',
    '🎣': 'fishing',
    '🥊': 'boxing glove',
    '🎽': 'running shirt',
    '🛹': 'skateboard',
    '⛸️': 'ice skating',
    '🎿': 'skiing',
    '🏂': 'snowboard',
    '🏆': 'trophy winner champion',
    '🥇': 'gold medal first',
    '🥈': 'silver medal second',
    '🥉': 'bronze medal third',
    '🏅': 'medal sports',
    '🎪': 'circus tent',
    '🎭': 'theater drama masks',
    '🎨': 'art palette painting',
    '🎬': 'movie clapper film',
    '🎤': 'microphone karaoke sing',
    '🎧': 'headphones music',
    '🎼': 'music score',
    '🎹': 'piano keyboard',
    '🥁': 'drum',
    '🎷': 'saxophone jazz',
    '🎺': 'trumpet',
    '🎸': 'guitar rock',
    '🎻': 'violin',
    '🎲': 'dice game',
    '🎯': 'bullseye target dart',
    '🎮': 'video game controller',
    '🕹️': 'joystick arcade',
    '🧩': 'puzzle piece jigsaw',
    '🚗': 'car automobile',
    '🚕': 'taxi cab',
    '🚌': 'bus',
    '🏎️': 'racing car',
    '🚓': 'police car',
    '🚑': 'ambulance',
    '🚒': 'fire truck',
    '🚚': 'delivery truck',
    '🚜': 'tractor',
    '🏍️': 'motorcycle',
    '🚲': 'bicycle bike',
    '✈️': 'airplane plane',
    '🚀': 'rocket space launch',
    '🛸': 'ufo flying saucer',
    '🚁': 'helicopter',
    '⛵': 'sailboat',
    '🚤': 'speedboat',
    '🚢': 'ship',
    '🏠': 'house home',
    '🏢': 'office building',
    '🏥': 'hospital',
    '🏫': 'school',
    '🏰': 'castle',
    '⛪': 'church',
    '📱': 'phone mobile smartphone',
    '💻': 'laptop computer',
    '⌨️': 'keyboard',
    '🖥️': 'desktop computer monitor',
    '🖨️': 'printer',
    '📷': 'camera photo',
    '📹': 'video camera',
    '📺': 'television tv',
    '📻': 'radio',
    '⏰': 'alarm clock time',
    '⌛': 'hourglass time',
    '💡': 'light bulb idea',
    '🔋': 'battery',
    '🔌': 'plug electric',
    '💰': 'money bag rich',
    '💳': 'credit card',
    '💎': 'gem diamond jewel',
    '🔧': 'wrench tool',
    '🔨': 'hammer tool',
    '🔩': 'nut bolt',
    '⚙️': 'gear settings',
    '🔫': 'gun water pistol',
    '💣': 'bomb explosive',
    '🔪': 'knife',
    '🛡️': 'shield',
    '🔮': 'crystal ball magic',
    '🧿': 'evil eye nazar',
    '💊': 'pill medicine',
    '💉': 'syringe needle vaccine',
    '🧬': 'dna',
    '🔬': 'microscope science',
    '🔭': 'telescope',
    '🧹': 'broom',
    '🚽': 'toilet',
    '🛁': 'bathtub bath',
    '🎉': 'party popper tada celebration confetti',
    '🔥': 'fire hot lit flame',
    '✨': 'sparkles stars magic glitter',
    '⭐': 'star',
    '🌟': 'glowing star',
    '💫': 'dizzy star',
    '☀️': 'sun sunny',
    '🌙': 'moon crescent night',
    '💤': 'sleeping zzz',
    '🏁': 'checkered flag finish race',
    '🚩': 'red flag',
    '🏴': 'black flag',
    '🏳️': 'white flag',
    '🏳️‍🌈': 'rainbow flag pride lgbtq',
    '🏴‍☠️': 'pirate flag',
    '🇩🇪': 'germany flag de',
    '🇦🇹': 'austria flag at',
    '🇨🇭': 'switzerland flag ch',
    '🇺🇸': 'usa america flag us',
    '🇬🇧': 'uk britain flag gb',
    '🇫🇷': 'france flag fr',
    '🇪🇸': 'spain flag es',
    '🇮🇹': 'italy flag it',
    '🇯🇵': 'japan flag jp',
    '🇨🇳': 'china flag cn',
    '🇷🇺': 'russia flag ru',
    '🇧🇷': 'brazil flag br',
    '🇮🇳': 'india flag in',
    '🇦🇺': 'australia flag au',
    '🇨🇦': 'canada flag ca',
    '🇺🇦': 'ukraine flag ua',
    '✅': 'check mark yes done',
    '❌': 'cross mark no wrong',
    '⭕': 'circle',
    '🛑': 'stop sign',
    '⛔': 'no entry forbidden',
    '🚫': 'prohibited banned',
    '💯': 'hundred perfect score',
    '♻️': 'recycling recycle',
    '⚠️': 'warning caution',
    ℹ️: 'information info',
    '❗': 'exclamation mark important',
    '❓': 'question mark',
    '👀': 'eyes looking watching',
    '👁️': 'eye',
    '👅': 'tongue',
    '👄': 'mouth lips',
    '👶': 'baby',
    '🧑': 'person adult',
    '👨': 'man',
    '👩': 'woman',
    '🧓': 'older person',
    '👴': 'old man',
    '👵': 'old woman',
    '🫶': 'heart hands love',
    '🫵': 'pointing at you',
    '⚔️': 'crossed swords battle fight',
    '🗡️': 'dagger knife sword',
    '🪙': 'coin money',
    '💵': 'dollar money bill',
    '💶': 'euro money',
    '💷': 'pound money',
    '🎫': 'ticket',
    '🎟️': 'admission ticket',
    '🎗️': 'ribbon awareness',
    '🎖️': 'military medal',
    '🏵️': 'rosette flower',
  }),
);

/** @type {Array<{id: string, icon: string, name: string, emojis: string[]}>} */
export const EMOJI_CATEGORIES = [
  {
    id: 'smileys',
    icon: '😀',
    name: 'Smileys',
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '🙃',
      '😉',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😗',
      '😚',
      '😙',
      '🥲',
      '😋',
      '😛',
      '😜',
      '🤪',
      '😝',
      '🤑',
      '🤗',
      '🤭',
      '🤫',
      '🤔',
      '🫡',
      '🤐',
      '🤨',
      '😐',
      '😑',
      '😶',
      '🫥',
      '😏',
      '😒',
      '🙄',
      '😬',
      '🤥',
      '😌',
      '😔',
      '😪',
      '🤤',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🥵',
      '🥶',
      '🥴',
      '😵',
      '🤯',
      '🤠',
      '🥳',
      '🥸',
      '😎',
      '🤓',
      '🧐',
      '😕',
      '🫤',
      '😟',
      '🙁',
      '☹️',
      '😮',
      '😯',
      '😲',
      '😳',
      '🥺',
      '🥹',
      '😦',
      '😧',
      '😨',
      '😰',
      '😥',
      '😢',
      '😭',
      '😱',
      '😖',
      '😣',
      '😞',
      '😓',
      '😩',
      '😫',
      '🥱',
      '😤',
      '😡',
      '😠',
      '🤬',
      '😈',
      '👿',
      '💀',
      '☠️',
      '💩',
      '🤡',
      '👹',
      '👺',
      '👻',
      '👽',
      '👾',
      '🤖',
      '😺',
      '😸',
      '😹',
      '😻',
      '😼',
      '😽',
      '🙀',
      '😿',
      '😾',
    ],
  },
  {
    id: 'people',
    icon: '👋',
    name: 'People',
    emojis: [
      '👋',
      '🤚',
      '🖐️',
      '✋',
      '🖖',
      '🫱',
      '🫲',
      '🫳',
      '🫴',
      '👌',
      '🤌',
      '🤏',
      '✌️',
      '🤞',
      '🫰',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '🖕',
      '👇',
      '☝️',
      '🫵',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '🫶',
      '👐',
      '🤲',
      '🤝',
      '🙏',
      '✍️',
      '💅',
      '🤳',
      '💪',
      '🦾',
      '🦿',
      '🦵',
      '🦶',
      '👂',
      '🦻',
      '👃',
      '🧠',
      '🫀',
      '🫁',
      '🦷',
      '🦴',
      '👀',
      '👁️',
      '👅',
      '👄',
      '🫦',
      '👶',
      '🧒',
      '👦',
      '👧',
      '🧑',
      '👱',
      '👨',
      '🧔',
      '👩',
      '🧓',
      '👴',
      '👵',
    ],
  },
  {
    id: 'animals',
    icon: '🐶',
    name: 'Animals & Nature',
    emojis: [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐻‍❄️',
      '🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐽',
      '🐸',
      '🐵',
      '🙈',
      '🙉',
      '🙊',
      '🐒',
      '🐔',
      '🐧',
      '🐦',
      '🐤',
      '🐣',
      '🐥',
      '🦆',
      '🦅',
      '🦉',
      '🦇',
      '🐺',
      '🐗',
      '🐴',
      '🦄',
      '🐝',
      '🪱',
      '🐛',
      '🦋',
      '🐌',
      '🐞',
      '🐜',
      '🪲',
      '🪳',
      '🦟',
      '🦗',
      '🕷️',
      '🕸️',
      '🦂',
      '🐢',
      '🐍',
      '🦎',
      '🦖',
      '🦕',
      '🐙',
      '🦑',
      '🦐',
      '🦞',
      '🦀',
      '🐡',
      '🐠',
      '🐟',
      '🐬',
      '🐳',
      '🐋',
      '🦈',
      '🪸',
      '🐊',
      '🐅',
      '🐆',
      '🦓',
      '🦍',
      '🦧',
      '🐘',
      '🦛',
      '🦏',
      '🐪',
      '🐫',
      '🦒',
      '🦘',
      '🌵',
      '🎄',
      '🌲',
      '🌳',
      '🌴',
      '🪵',
      '🌱',
      '🌿',
      '☘️',
      '🍀',
      '🎍',
      '🪴',
      '🎋',
      '🍃',
      '🍂',
      '🍁',
      '🌾',
      '🌺',
      '🌻',
      '🌹',
      '🥀',
      '🌷',
      '🌼',
      '🌸',
      '💐',
      '🍄',
      '🌰',
      '🎃',
      '🐚',
      '🪨',
      '🌎',
      '🌍',
      '🌏',
      '🌕',
      '🌙',
      '⭐',
      '🌟',
      '💫',
      '✨',
      '☀️',
      '🌈',
    ],
  },
  {
    id: 'food',
    icon: '🍕',
    name: 'Food & Drink',
    emojis: [
      '🍇',
      '🍈',
      '🍉',
      '🍊',
      '🍋',
      '🍌',
      '🍍',
      '🥭',
      '🍎',
      '🍏',
      '🍐',
      '🍑',
      '🍒',
      '🍓',
      '🫐',
      '🥝',
      '🍅',
      '🫒',
      '🥥',
      '🥑',
      '🍆',
      '🥔',
      '🥕',
      '🌽',
      '🌶️',
      '🫑',
      '🥒',
      '🥬',
      '🥦',
      '🧄',
      '🧅',
      '🍄',
      '🥜',
      '🫘',
      '🌰',
      '🍞',
      '🥐',
      '🥖',
      '🫓',
      '🥨',
      '🥯',
      '🥞',
      '🧇',
      '🧀',
      '🍖',
      '🍗',
      '🥩',
      '🥓',
      '🍔',
      '🍟',
      '🍕',
      '🌭',
      '🥪',
      '🌮',
      '🌯',
      '🫔',
      '🥙',
      '🧆',
      '🥚',
      '🍳',
      '🥘',
      '🍲',
      '🫕',
      '🥣',
      '🥗',
      '🍿',
      '🧈',
      '🧂',
      '🥫',
      '🍱',
      '🍘',
      '🍙',
      '🍚',
      '🍛',
      '🍜',
      '🍝',
      '🍠',
      '🍢',
      '🍣',
      '🍤',
      '🍥',
      '🥮',
      '🍡',
      '🥟',
      '🥠',
      '🥡',
      '🦀',
      '🦞',
      '🦐',
      '🦑',
      '🦪',
      '🍦',
      '🍧',
      '🍨',
      '🍩',
      '🍪',
      '🎂',
      '🍰',
      '🧁',
      '🥧',
      '🍫',
      '🍬',
      '🍭',
      '🍮',
      '🍯',
      '🍼',
      '🥛',
      '☕',
      '🫖',
      '🍵',
      '🍶',
      '🍾',
      '🍷',
      '🍸',
      '🍹',
      '🍺',
      '🍻',
      '🥂',
      '🥃',
      '🫗',
      '🥤',
      '🧋',
      '🧃',
      '🧉',
      '🧊',
    ],
  },
  {
    id: 'hearts',
    icon: '❤️',
    name: 'Hearts & Symbols',
    emojis: [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❤️‍🔥',
      '❤️‍🩹',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '💋',
      '💯',
      '💢',
      '💥',
      '💫',
      '💦',
      '💨',
      '💬',
      '💭',
      '💤',
      '✅',
      '❌',
      '⭕',
      '🛑',
      '⛔',
      '🚫',
      '💯',
      '♻️',
      '⚠️',
      'ℹ️',
      '❗',
      '❓',
      '⭐',
      '🌟',
      '✨',
      '🔥',
      '🎉',
      '🎊',
    ],
  },
  {
    id: 'activities',
    icon: '⚽',
    name: 'Activities',
    emojis: [
      '⚽',
      '🏀',
      '🏈',
      '⚾',
      '🥎',
      '🎾',
      '🏐',
      '🏉',
      '🥏',
      '🎱',
      '🪀',
      '🏓',
      '🏸',
      '🏒',
      '🥍',
      '🏑',
      '🥅',
      '⛳',
      '🪃',
      '🏹',
      '🎣',
      '🤿',
      '🥊',
      '🥋',
      '🎽',
      '🛹',
      '🛼',
      '🛷',
      '⛸️',
      '🥌',
      '🎿',
      '⛷️',
      '🏂',
      '🪂',
      '🏋️',
      '🤼',
      '🤸',
      '⛹️',
      '🤺',
      '🤾',
      '🏇',
      '🧘',
      '🏄',
      '🏊',
      '🤽',
      '🚣',
      '🧗',
      '🚵',
      '🚴',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
      '🏅',
      '🎖️',
      '🏵️',
      '🎗️',
      '🎫',
      '🎟️',
      '🎪',
      '🤹',
      '🎭',
      '🩰',
      '🎨',
      '🎬',
      '🎤',
      '🎧',
      '🎼',
      '🎹',
      '🥁',
      '🪘',
      '🎷',
      '🎺',
      '🪗',
      '🎸',
      '🪕',
      '🎻',
      '🎲',
      '♟️',
      '🎯',
      '🎳',
      '🎮',
      '🕹️',
      '🧩',
    ],
  },
  {
    id: 'travel',
    icon: '🚗',
    name: 'Travel',
    emojis: [
      '🚗',
      '🚕',
      '🚙',
      '🚌',
      '🚎',
      '🏎️',
      '🚓',
      '🚑',
      '🚒',
      '🚐',
      '🛻',
      '🚚',
      '🚛',
      '🚜',
      '🏍️',
      '🛵',
      '🚲',
      '🛴',
      '🛺',
      '✈️',
      '🛫',
      '🛬',
      '🚀',
      '🛸',
      '🚁',
      '⛵',
      '🚤',
      '🚢',
      '🏠',
      '🏡',
      '🏢',
      '🏥',
      '🏫',
      '🏰',
      '⛪',
      '🗽',
      '🗼',
      '🎡',
      '🎢',
      '⛲',
      '🏖️',
      '🏝️',
      '⛰️',
      '🏔️',
      '🌋',
      '🏕️',
    ],
  },
  {
    id: 'objects',
    icon: '💡',
    name: 'Objects',
    emojis: [
      '📱',
      '💻',
      '⌨️',
      '🖥️',
      '🖨️',
      '🖱️',
      '💽',
      '💾',
      '💿',
      '📀',
      '📷',
      '📸',
      '📹',
      '🎥',
      '📺',
      '📻',
      '🎙️',
      '🎚️',
      '🎛️',
      '⏰',
      '⌛',
      '📡',
      '🔋',
      '🔌',
      '💡',
      '🔦',
      '🕯️',
      '💰',
      '💵',
      '💶',
      '💷',
      '🪙',
      '💳',
      '💎',
      '📧',
      '📨',
      '📩',
      '📦',
      '📋',
      '📎',
      '🔏',
      '🔐',
      '🔑',
      '🗝️',
      '🔧',
      '🔨',
      '🔩',
      '⚙️',
      '🛠️',
      '⛏️',
      '🗡️',
      '⚔️',
      '🛡️',
      '🔫',
      '💣',
      '🔮',
      '🧿',
      '💊',
      '💉',
      '🧬',
      '🔬',
      '🔭',
      '🧹',
      '🚽',
      '🛁',
    ],
  },
  {
    id: 'flags',
    icon: '🏁',
    name: 'Flags',
    emojis: [
      '🏁',
      '🚩',
      '🎌',
      '🏴',
      '🏳️',
      '🏳️‍🌈',
      '🏳️‍⚧️',
      '🏴‍☠️',
      '🇩🇪',
      '🇦🇹',
      '🇨🇭',
      '🇺🇸',
      '🇬🇧',
      '🇫🇷',
      '🇪🇸',
      '🇮🇹',
      '🇵🇹',
      '🇧🇷',
      '🇯🇵',
      '🇰🇷',
      '🇨🇳',
      '🇷🇺',
      '🇮🇳',
      '🇦🇺',
      '🇨🇦',
      '🇲🇽',
      '🇳🇱',
      '🇧🇪',
      '🇸🇪',
      '🇳🇴',
      '🇩🇰',
      '🇫🇮',
      '🇵🇱',
      '🇨🇿',
      '🇭🇺',
      '🇷🇴',
      '🇬🇷',
      '🇹🇷',
      '🇮🇱',
      '🇸🇦',
      '🇦🇪',
      '🇿🇦',
      '🇪🇬',
      '🇳🇬',
      '🇰🇪',
      '🇦🇷',
      '🇨🇴',
      '🇨🇱',
      '🇵🇪',
      '🇻🇪',
      '🇹🇭',
      '🇻🇳',
      '🇵🇭',
      '🇮🇩',
      '🇲🇾',
      '🇸🇬',
      '🇳🇿',
      '🇮🇪',
      '🇺🇦',
      '🇭🇷',
    ],
  },
];
